spring:
#  mvc:
#    static-path-pattern: /res/**
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true



  resources:
    static-locations: [classpath:/haha/]